...
----------------------------------------------------------------------
Ran 3 tests in 0.943s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.517s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.590s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.679s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.647s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.670s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.583s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.604s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.555s

OK
.F.
======================================================================
FAIL: test_add_user (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unit_test.py", line 35, in test_add_user
    self.assertEqual(UserController.add_user(self.user_1), 'SUCCESS')
AssertionError: 'DUPLICATE' != 'SUCCESS'
- DUPLICATE
+ SUCCESS


----------------------------------------------------------------------
Ran 3 tests in 1.893s

FAILED (failures=1)
...
----------------------------------------------------------------------
Ran 3 tests in 2.473s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.619s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.636s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.666s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.549s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.694s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.497s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.521s

OK
.F.
======================================================================
FAIL: test_add_user (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unit_test.py", line 35, in test_add_user
    self.assertEqual(UserController.add_user(self.user_1), 'SUCCESS')
AssertionError: 'DUPLICATE' != 'SUCCESS'
- DUPLICATE
+ SUCCESS


----------------------------------------------------------------------
Ran 3 tests in 1.991s

FAILED (failures=1)
...
----------------------------------------------------------------------
Ran 3 tests in 2.676s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.476s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.595s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.466s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.598s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.664s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.452s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.673s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.662s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.691s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.438s

OK
.F.
======================================================================
FAIL: test_add_user (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unit_test.py", line 35, in test_add_user
    self.assertEqual(UserController.add_user(self.user_1), 'SUCCESS')
AssertionError: 'DUPLICATE' != 'SUCCESS'
- DUPLICATE
+ SUCCESS


----------------------------------------------------------------------
Ran 3 tests in 1.948s

FAILED (failures=1)
...
----------------------------------------------------------------------
Ran 3 tests in 2.624s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 2.585s

OK
.F.
======================================================================
FAIL: test_add_user (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unit_test.py", line 35, in test_add_user
    self.assertEqual(UserController.add_user(self.user_1), 'SUCCESS')
AssertionError: 'DUPLICATE' != 'SUCCESS'
- DUPLICATE
+ SUCCESS


----------------------------------------------------------------------
Ran 3 tests in 1.774s

FAILED (failures=1)
...
----------------------------------------------------------------------
Ran 3 tests in 2.643s

OK
